version: '2.4'
services:
  apache:
    image: httpd:latest
    container_name: nodejschatapp
    enviroment:
    - 'PORT:3000'
    ports:
    - '80:3000'
    volumes:
    - ./:/usr/local/apache2/htdocs
